# Exported from Render on 2025-09-05T08:26:36Z
services:
- type: web
  name: H2Herbal1
  runtime: python
  repo: https://github.com/Kuameyangseo/H2Herbal1
  plan: free
  envVars:
  - key: TWILIO_PHONE_NUMBER
    sync: false
  - key: TWILIO_AUTH_TOKEN
    sync: false
  - key: TWILIO_ACCOUNT_SID
    sync: false
  - key: BASE_URL
    sync: false
  - key: PAYSTACK_PUBLIC_KEY
    sync: false
  - key: PAYSTACK_SECRET_KEY
    sync: false
  - key: MAIL_DEFAULT_SENDER
    sync: false
  - key: MAIL_PASSWORD
    sync: false
  - key: MAIL_USERNAME
    sync: false
  - key: MAIL_USE_TLS
    sync: false
  - key: MAIL_PORT
    sync: false
  - key: MAIL_SERVER
    sync: false
  - key: GOOGLE_CLIENT_SECRET
    sync: false
  - key: GOOGLE_CLIENT_ID
    sync: false
  - key: DATABASE_URL
    sync: false
  - key: FLASK_DEBUG
    sync: false
  - key: FLASK_ENV
    sync: false
  - key: SECRET_KEY
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
  autoDeployTrigger: commit
version: "1"
